version: '1.0.{build}'
image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release
  - Debug

environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg install sdl2 sdl2-image sdl2-image[libjpeg-turbo] sdl2-image[tiff] sdl2-image[libwebp] sdl2-mixer sdl2-mixer[dynamic-load] sdl2-mixer[libflac] sdl2-mixer[mpg123] sdl2-mixer[libmodplug] sdl2-mixer[libvorbis] sdl2-mixer[opusfile] sdl2-ttf nlohmann-json sol2 fmt
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16 2019"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\TnT.sln

cache: c:\tools\vcpkg\installed\