# TODO: 
# 1. add different builds for x86/x64.
# 2. check for updates weekly.

trigger:
- master

jobs:
  - job: "Build"
    strategy:
      matrix:
        linux:
          Image: 'ubuntu-latest'
          vpath: "/usr/local/share/vcpkg/installed/x64-linux"
          get_yasm: "sudo apt-get install yasm"
          triplet: x64-linux
        windows:
          Image: 'windows-latest'
          vpath: "C:\\vcpkg\\installed\\x64-windows"
          get_yasm: "echo" # on Windows, yasm is automatically installed if missing
          triplet: x64-windows
        mac:
          Image: 'macos-latest'
          vpath: "/usr/local/share/vcpkg/installed/x64-osx"
          get_yasm: "brew install yasm"
          triplet: x64-osx
      maxParallel: 4
    variables:
      VCPKG_DEFAULT_TRIPLET: $(triplet)
    
    pool:
      vmImage: $(Image)
    
    steps:
    - task: Cache@2
      inputs:
        key: 'CACHED_DEPS'
        path: '$(vpath)'
        cacheHitVar: 'GOT_CACHE'

    - task: CmdLine@2
      inputs:
        script: |
          $(get_yasm)
          vcpkg install sdl2 sdl2-image sdl2-net sdl2-image[libjpeg-turbo] sdl2-image[tiff] sdl2-image[libwebp] sdl2-mixer sdl2-mixer[dynamic-load] sdl2-mixer[libflac] sdl2-mixer[mpg123] sdl2-mixer[libmodplug] sdl2-mixer[libvorbis] sdl2-mixer[opusfile] sdl2-ttf nlohmann-json sol2 fmt
          vcpkg integrate install
      condition: ne(variables.GOT_CACHE, 'true')
    
    - task: CMake@1
      inputs:
        cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$(vpath)/scripts/buildsystem/vcpkg.cmake'
    displayName: 'Build for '

  - job: "MSBuild_Windows"
    dependsOn: Build
    condition: succeeded()
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: VSBuild@1
      inputs:
        solution: 'build\TnT.sln'
        platform: 'x64'
        configuration: 'Debug'
        clean: true
        maximumCpuCount: true
        msbuildArchitecture: 'x64'
        createLogFile: true
    - task: VSBuild@1
      inputs:
        solution: 'build\TnT.sln'
        vsVersion: 'latest'
        platform: 'x64'
        configuration: 'Release'
        clean: true
        maximumCpuCount: true
        msbuildArchitecture: 'x64'
        createLogFile: true