trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      triplet: 'x64-linux'
    windows:
      imageName: 'windows-latest'
      triplet: 'x64-windows'


pool:
  vmImage: $(imageName)


steps:
  - script: vcpkg install fmt sol2 nlohmann-json sdl2 sdl2-image sdl2-mixer sdl2-ttf sdl2-net
    env:
      VCPKG_DEFAULT_TRIPLET: $(triplet)
    name: "get_dependencies"

  - script: vcpkg integrate install
    env:
      VCPKG_DEFAULT_TRIPLET: $(triplet)
    name: "integrate_dependencies"