# TODO: 
# 1. add cache support.
# 2. add different builds for x86/x64.
# 3. check for updates weekly.
# 4. copy files from assets to Debug/Release

trigger:
- master

jobs:
  - job: "GetDeps"
    strategy:
      matrix:
        linux:
          Image: 'ubuntu-latest'
          vpath: "/usr/local/share/vcpkg/installed/x64-linux"
          toolpath: "/usr/local/share/vcpkg/downloads/tools"
          triplet: x64-linux
        windows:
          Image: 'windows-latest'
          vpath: "C:\\vcpkg\\installed\\x64-windows"
          toolpath: "C:\\vcpkg\\downloads\\tools"
          triplet: x64-windows
        mac:
          Image: 'macos-latest'
          vpath: "/usr/local/share/vcpkg/installed/x64-osx"
          toolpath: "/usr/local/share/vcpkg/downloads/tools"
          triplet: x64-osx
    variables:
      VCPKG_DEFAULT_TRIPLET: $(triplet)
    
    pool:
      vmImage: $(Image)
    
    steps:
    # - task: Cache@2
    #   inputs:
    #     key: '$(Image)_dependencies'
    #     path: '$(vpath)'
    #     cacheHitVar: 'GOT_CACHE'
    # - task: Cache@2
    #   inputs:
    #     key: '$(Image)_vcpkg_tools'
    #     path: '$(toolpath)'
    #     cacheHitVar: 'GOT_TOOLS_CACHE'
    - script: |
          vcpkg install sdl2 sdl2-image sdl2-image[libjpeg-turbo, tiff, libwebp] sdl2-mixer sdl2-mixer[dynamic-load, libflac, mpg123, libmodplug, libvorbis, opusfile] sdl2-ttf nlohmann-json sol2 fmt
          vcpkg integrate install
      # condition: or(ne(variables.GOT_CACHE, 'true'), ne(variables.GOT_TOOLS_CACHE, 'true'))
      displayName: 'Get dependencies'
  
  - job: "Run_CMake"
    strategy:
      matrix: 
        # linux:
        #     Image: 'ubuntu-latest'
        windows:
            Image: 'windows-latest'
            lua_inc: "C:\\vcpkg\\installed\\x64-windows\\include"
            lua_lib: "C:\\vcpkg\\installed\\x64-windows\\lib"
            sdl_dir: "C:\\vcpkg\\installed\\x64-windows\\share\\sdl2"
        mac:
            Image: 'macos-latest'
            lua_inc: "/usr/local/share/vcpkg/installed/x64-osx/include"
            lua_lib: "/usr/local/share/vcpkg/installed/x64-osx/lib"
            sdl_dir: "/usr/local/share/vcpkg/installed/x64-osx/share/sdl2"
      maxParallel: 4

    variables:
      LUA_INCLUDE_DIR: $(lua_inc)
      LUA_LIBRARIES: $(lua_lib)
      SDL2_DIR: $(sdl_dir)


    pool:
      vmImage: $(Image)

    steps:
      - task: CMake@1
        inputs:
          cmakeArgs: '..'

  - job: "MSBuild_Windows"
    dependsOn: Run_CMake
    condition: succeeded()
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: VSBuild@1
      inputs:
        solution: 'build\TnT.sln'
        platform: 'x64'
        configuration: 'Debug'
        clean: true
        maximumCpuCount: true
        msbuildArchitecture: 'x64'
        createLogFile: true
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'assets'
        Contents: '**'
        TargetFolder: 'build/Debug'
    - task: VSBuild@1
      inputs:
        solution: 'build\TnT.sln'
        vsVersion: 'latest'
        platform: 'x64'
        configuration: 'Release'
        clean: true
        maximumCpuCount: true
        msbuildArchitecture: 'x64'
        createLogFile: true
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'assets'
        Contents: '**'
        TargetFolder: 'build/Release'