# (DONE) find a way to add SDL2 to the build system.
# (DONE) find a way to check if there is a new version of the dependencies and update automatically.
# (DONE) handle vcpkg actions better.
# (DONE) consider building all the dependencies in a single action.
# (DONE) using env: set vcpkg triplet to x64.
# (DONE) build vcpkg on macosx after downloading.

# TODO:
# 1. (maybe)(PARTIAL) add more os-es and more build configurations.
# 2. consider using CMake to convert TnT into a Visual Studio solution/GCC/Clang project.
# 3. (NEEDS TESTING) cache installed packages and run vcpkg update once a week.
# 4. check for vcpkg updates weekly on macosx.
# 5. The runner on Windows doesn't know the location of vcvars64.bat. Add that to the PATH using env:.
# 6. actions/cache knows there is some cache saved, but still runs downlod process. FIX THAT!!!
# 7. Use PVS-Studio for statical analysis on every commit.

name: CI
on: [push]

jobs:
    get-dependencies:
        name: ${{ matrix.os }}-dependencies
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [windows-latest, ubuntu-latest , macos-latest]
            include:
              - os: windows-latest
                triplet: x64-windows
                vcpkg-path: "%VCPKG_INSTALLATION_PATH%\\installed\\x64-windows"
                run: |
                     vcvars64
                     mkdir build && cd build
                     cmake ..
              - os: ubuntu-latest
                triplet: x64-linux
                vcpkg-path: "$VCPKG_INSTALLATION_PATH/installed/x64-linux"
                run: |
                    mkdir build && cd build
                    cmake ..
              - os: macos-latest
                vcpkg-path: "$VCPKG_INSTALLATION_PATH/installed/x64-linux"
                triplet: x64-osx


        steps:
          - name: Run vcpkg
            env:
              VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
            if: steps.pack-cache.outputs.cache-hit != 'true'
            run: vcpkg install fmt sol2 nlohmann-json sdl2 sdl2-image sdl2-mixer sdl2-ttf sdl2-net
          - name: Cache packages
            id: pack-cache
            uses: actions/cache@v1.1.2
            with:
             path: ${{ matrix.vcpkg-path }}
             key: ${{ matrix.os }}-dependencies
          - name: Integrate packages
            run: vcpkg integrate install


    tnt:
            runs-on: ${{matrix.os}}
            needs: [get-dependencies]
            name: Build TnT
            steps:
            - uses: actions/checkout@v2
            - name: Build TnT.exe
              run: ${{ matrix.run }}
