# (DONE) find a way to add SDL2 to the build system.
# (DONE) find a way to check if there is a new version of the dependencies and update automatically.
# (DONE) handle vcpkg actions better.
# (DONE) consider building all the dependencies in a single action.

# TODO:
# 1. (maybe)(PARTIAL) add more os-es and more build configurations.
# 2. (PARTIAL) make this cross-platform.
# 3. consider using CMake to convert TnT into a Visual Studio solution/GCC/Clang project.
# 4. vcpkg isn't pre-installed on macOSX. Fix that.
# 5. cache installed packages and run vcpkg update once a week.
# 6. using env: set vcpkg triplet to x64

name: CI

on: [push]

jobs:
  get-dependencies:
    name: ${{ matrix.os }}-dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            compiler: cl.exe
            build: /EHsc /std:c++latest /O2 /W4 /Iinclude main.cpp src\*.cpp /FeTnT.exe /Fo.\obj\ /link /subsystem:console /machine:x64
            vcpkg-path: C:\\vcpkg\\installed\\x64-windows
            triplet: x64-windows
            separator: \\
          - os: ubuntu-latest
            compiler: gcc
            vcpkg-path: /usr/local/share/vcpkg/installed/x64-linux
            separator: /
            triplet: x64-linux
          - os: macos-latest
            compiler: clang 
            vcpkg-path: sth
            separator: /
            triplet: x64-osx

            
    steps:
      - name: Run vcpkg
        env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
        run: vcpkg install fmt sol2 nlohmann-json sdl2 sdl2-image sdl2-mixer sdl2-ttf sdl2-net
      - name: Linux find vcpkg
        run: ${{ matrix.find }}
      - name: Cache packages
        uses: actions/chache@v1.1.2
        with:
         path: ${{ matrix.vcpkg-path }}
      - name: Integrate packages
        run: vcpkg integrate install

    
  tnt:
    runs-on: [windows-latest]
    needs: [get-dependencies]
    name: Build TnT
    steps:
      - uses: actions/checkout@v1
      - name: Build TnT.exe
        run: |
          dir
          mkdir obj
          cl /EHsc /std:c++latest /O2 /W4 /Iinclude main.cpp src\*.cpp /FeTnT.exe /Fo.\obj\ /link /subsystem:console /machine:x64
