# (DONE) find a way to add SDL2 to the build system.
# (DONE) find a way to check if there is a new version of the dependencies and update automatically.
# (DONE) handle vcpkg actions better.
# (DONE) consider building all the dependencies in a single action.
# (DONE) using env: set vcpkg triplet to x64.
# (DONE) build vcpkg on macosx after downloading.

# TODO:
# 1. (maybe)(PARTIAL) add more os-es and more build configurations.
# 2. consider using CMake to convert TnT into a Visual Studio solution/GCC/Clang project.
# 3. vcpkg isn't pre-installed on macOSX. Fix that. Also, cache the installation.
# 4. (NEEDS TESTING) cache installed packages and run vcpkg update once a week.
# 5. check for vcpkg updates weekly on macosx.
# 6. The runner on Windows doesn't know the location of vcvars64.bat. Add that to the PATH using env:.
# 7. actions/cache knows there is some cache saved, but atill runs downlod process. FIX THAT!!!
# 8. Use PVS-Studio for statical analysis on every commit.

name: CI
on: [push]

# jobs:
#   dl-vcpkg:
#     name: Download vcpkg
#     runs-on: [macos-latest]
#     steps:
#       - name: Cache vcpkg
#         id: vcpkg-macos-cache
#       - uses: actions/cache@v1.1.2
#         with:
#          path: vcpkg
#          key: mac-vcpkg

#       - name: Download vcpkg
#         if: steps.vcpkg-macos-cache.outputs.cache-hit != 'true'
#         run: |
#           pwd
#           git clone https://www.github.com/microsoft/vcpkg.git
#           cd vcpkg
#           ./bootstrap-vcpkg.sh

jobs:
    get-dependencies:
        name: ${{ matrix.os }}-dependencies
        # needs: [dl-vcpkg]
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [windows-latest, ubuntu-latest] #, macos-latest]
            include:
              - os: windows-latest
                compiler: cl.exe
                build: /EHsc /std:c++latest /O2 /W4 /Iinclude main.cpp src\*.cpp /FeTnT.exe /Fo.\obj\ /link /subsystem:console /machine:x64
                vcpkg-path: C:\\vcpkg\\installed\\x64-windows
                triplet: x64-windows
                exe: vcpkg
              - os: ubuntu-latest
                compiler: gcc
                vcpkg-path: /usr/local/share/vcpkg/installed/x64-linux
                triplet: x64-linux
                exe: vcpkg
              # - os: macos-latest
              #   compiler: clang 
              #   vcpkg-path: sth
              #   triplet: x64-osx
              #   exe: ./vcpkg


        steps:
          - name: Run vcpkg
            env:
              VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
            if: steps.pack-cache.outputs.cache-hit != 'true'
            run: vcpkg install fmt sol2 nlohmann-json sdl2 sdl2-image sdl2-mixer sdl2-ttf sdl2-net
          - name: Cache packages
            id: pack-cache
            uses: actions/cache@v1.1.2
            with:
             path: ${{ matrix.vcpkg-path }}
             key: dependencies
          - name: Integrate packages
            run: ${{ matrix.exe }} integrate install


    tnt:
            runs-on: [windows-latest]
            needs: [get-dependencies]
            name: Build TnT
            steps:
            - uses: actions/checkout@v2
            - name: Build TnT.exe
              run: |
                vcvars64
                mkdir obj
                cl /EHsc /std:c++latest /O2 /W4 /Iinclude main.cpp src\*.cpp /FeTnT.exe /Fo.\obj\ /link /subsystem:console /machine:x64
