name: CI

on: [push]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Run a one-line build script using cl.exe
      run: cl /EHsc /std:c++latest /O2 /W4 main.cpp src\*.cpp /FeTnT.exe /link /subsystem:console /machine:x64
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
