# TODO: 
# 1. find a way to add SDL2 to the build system.
# 2. (maybe) build every dependency with CMake, and then build their solution with msbuild.
# 3. find a way to check if there is a new version of the dependencies and update automatically.

name: CI

on: [push]

jobs:
  fmt:
    runs-on: [windows-latest]
    name: Build fmtlib
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/run-vcpkg@v0.8
      - name: fmtlib.dll
        shell: cmd
        run: |
          vcpkg install fmt

    
  sol2:
    runs-on: [windows-latest]
    name: Build sol2
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/run-vcpkg@v0.8
      - name: sol2 build
        shell: cmd
        run: |
          vcpkg install sol2
        
        
  json:
    runs-on: [windows-latest]
    name: Build json
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/run-vcpkg@v0.8
      - name: nlohmann-json
        shell: cmd
        run: |
          vcpkg install nlohmann-json
          
  sdl2:
    runs-on: [windows-latest]
    name: Build sdl2
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/run-vcpkg@v0.8
      - name: SDL2
        shell: cmd
        run: |
          vcpkg install sdl2 sdl2-net sdl2-image sdl2-mixer sdl2-ttf
          
    
  integrate:
    runs-on: [windows-latest]
    name:  Integrate all installed packages with the build system
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/run-vcpkg@v0.8
      - name: integrate
        shell: cmd
        run: |
          vcpkg integrate install
    
  tnt:
    runs-on: [windows-latest]
    needs: [fmt, json, sol2]
    name: Build TnT
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/run-vcpkg@v0.8
      - name: Build TnT.exe
        shell: cmd
        run: |
          dir
          mkdir obj
          cl /EHsc /std:c++latest /O2 /W4 /Iinclude main.cpp src\*.cpp /FeTnT.exe /Fo.\obj\ /link /subsystem:console /machine:x64
          cls
