name: CI

on: [push]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build TnT.exe
      run: cl /EHsc /std:c++latest /O2 /W4 main.cpp src\*.cpp /FeTnT.exe /link /subsystem:console /machine:x64