# TODO: 
# 1. find a way to add SDL2 to the build system.
# 2. (maybe) build every dependency with CMake, and then build their solution with msbuild.
# 3. find a way to check if there is a new version of the dependencies and update automatically.
# 4. handle vcpkg actions better.
# 5. (maybe) add more os-es and more build configurations.
# 6. make this cross-platform
# 7. consider building all the dependencies in a single action.

name: CI

on: [push]

jobs:
  get-dependencies:
    name: ${{ matrix.os }}-dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgPackages: 'fmt sol2 nlohmann-json sdl2 sdl2-image sdl2-mixer sdl2-ttf sdl2-net'
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgPackages: 'fmt sol2 nlohmann-json sdl2 sdl2-image sdl2-mixer sdl2-ttf sdl2-net'
          - os: macos-latest
            triplet:  x64-osx
            vcpkgPackages: 'fmt sol2 nlohmann-json sdl2 sdl2-image sdl2-mixer sdl2-ttf sdl2-net'
            
    steps:
      - uses: actions/checkout@v2
      - uses: actions/chache@v1.1.2
      - uses: lukka/run-vcpkg@v0.8
        with:
          submodules: true
      - name:  dependencies
        shell: cmd
        
    
  tnt:
    runs-on: [windows-latest]
    needs: [get-dependencies]
    name: Build TnT
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/run-vcpkg@v0.8
      - name: Build TnT.exe
        shell: cmd
        run: |
          dir
          mkdir obj
          cl /EHsc /std:c++latest /O2 /W4 /Iinclude main.cpp src\*.cpp /FeTnT.exe /Fo.\obj\ /link /subsystem:console /machine:x64
          cls
